### ISSUE TITLE
Final Battle goes Null

### ISSUE THREAD

**Issue by alchemistake** [alchemistake/betaPika#5]
Process CollectorProcess-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Volumes/ALCHE SD/betaPika/Collector/collector.py", line 129, in run
    self.cycle_open_battles()
  File "/Volumes/ALCHE SD/betaPika/Collector/collector.py", line 167, in cycle_open_battles
    self.rejoin_and_download(battle)
  File "/Volumes/ALCHE SD/betaPika/Collector/collector.py", line 190, in rejoin_and_download
    ".firstChild.firstChild.firstChild.firstChild.click();")
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 491, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: TypeError: document.getElementById(...).children[4].firstChild.firstChild.firstChild.firstChild is null

**Comment by alchemistake** [comment]
Traceback (most recent call last):
  File "/Volumes/ALCHE SD/betaPika/Collector/collector.py", line 121, in run
    self.join_new_battles()
  File "/Volumes/ALCHE SD/betaPika/Collector/collector.py", line 163, in join_new_battles
    battles = self.refresh_battles()
  File "/Volumes/ALCHE SD/betaPika/Collector/collector.py", line 254, in refresh_battles
    return json.loads(result.split("|")[-1])
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 3199 (char 3198)
